#!/usr/bin/env python3
"""
generate_scorecard_pdf.py

Generate a 2-page branded candidate scorecard PDF for TalentCollyde Hire.

Page 1: Candidate snapshot + composite + recommendation + gates + persona.
Page 2: Weighted scoring table + counter-cases + provenance + TalentCollyde footer.

Brand palette (TalentCollyde — locked):
  - Charcoal:        #1a1a2e   (primary dark — headings, dark surfaces, body text)
  - Warm White:      #faf9f7   (page background, light text on dark surfaces)
  - Off White:       #f0eeeb   (alternate section background)
  - Sand:            #e8e4df   (borders, dividers)
  - Gold:            #c9a96e   (TalentCollyde accent — default when no company hex)
  - Text Secondary:  #5a5a7a   (supporting copy)

The user's company accent color is passed via --client-accent and used for:
  - The score-bar fills
  - Section underline accents
  - The recommendation chip

If no client accent is provided, falls back to TalentCollyde Gold.

The TalentCollyde brand-impression footer is non-negotiable — every PDF carries
the "Want this run for you? talentcollyde.com" line as the final element.

Input: JSON file matching the schema in
  skills/scorecard/templates/scorecard_data_schema.md.
Output: a 2-page PDF.

Dependencies:
  - reportlab  (pip install reportlab --break-system-packages)

Usage:
  python3 generate_scorecard_pdf.py \
    --input scorecard-data.json \
    --output scorecard.pdf \
    --client-accent "#FE5A27" \
    --company-name "Acme Inc"
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from datetime import datetime
from typing import Any

try:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import LETTER
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import (
        BaseDocTemplate,
        Flowable,
        Frame,
        PageBreak,
        PageTemplate,
        Paragraph,
        Spacer,
        Table,
        TableStyle,
    )
except ImportError:
    sys.stderr.write(
        "ERROR: reportlab is not installed. Install with:\n"
        "  pip install reportlab --break-system-packages\n"
    )
    sys.exit(2)


# --- Brand ------------------------------------------------------------------

CHARCOAL = colors.HexColor("#1a1a2e")
WARM_WHITE = colors.HexColor("#faf9f7")
OFF_WHITE = colors.HexColor("#f0eeeb")
SAND = colors.HexColor("#e8e4df")
GOLD = colors.HexColor("#c9a96e")
TEXT_SECONDARY = colors.HexColor("#5a5a7a")
DEFAULT_ACCENT = GOLD

HEX_RE = re.compile(r"^#[0-9A-Fa-f]{6}$")

TC_FOOTER_LINE = (
    "Generated by TalentCollyde Hire — founder-grade hiring intelligence. "
    "Want this run for you on every candidate, end-to-end? talentcollyde.com"
)


# --- Helpers ----------------------------------------------------------------

def hex_or_default(hex_str: str | None) -> colors.Color:
    if hex_str and HEX_RE.match(hex_str):
        return colors.HexColor(hex_str)
    return DEFAULT_ACCENT


def safe(value: Any, default: str = "—") -> str:
    if value is None:
        return default
    if isinstance(value, str) and value.strip() == "":
        return default
    return str(value)


def _xml_escape(text: Any) -> str:
    if text is None:
        text = ""
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def para(text: Any, style: ParagraphStyle) -> Paragraph:
    return Paragraph(_xml_escape(text), style)


def rp(markup: str, style: ParagraphStyle, **fields: Any) -> Paragraph:
    safe_fields = {k: _xml_escape(v) for k, v in fields.items()}
    return Paragraph(markup.format(**safe_fields), style)


# --- Custom flowables -------------------------------------------------------

class HRule(Flowable):
    def __init__(self, width: float, color: colors.Color, thickness: float = 0.6):
        super().__init__()
        self.width = width
        self.color = color
        self.thickness = thickness
        self.height = thickness

    def draw(self) -> None:
        self.canv.setStrokeColor(self.color)
        self.canv.setLineWidth(self.thickness)
        self.canv.line(0, 0, self.width, 0)


class ScoreBar(Flowable):
    def __init__(
        self,
        score: float,
        max_score: float,
        width: float,
        accent: colors.Color,
        height: float = 16,
    ):
        super().__init__()
        self.score = max(0.0, min(float(score or 0), float(max_score)))
        self.max_score = float(max_score)
        self.width = width
        self.height = height
        self.accent = accent

    def draw(self) -> None:
        c = self.canv
        c.setFillColor(OFF_WHITE)
        c.setStrokeColor(SAND)
        c.setLineWidth(0.5)
        c.roundRect(0, 0, self.width, self.height, 3, stroke=1, fill=1)
        fill_w = self.width * (self.score / self.max_score if self.max_score else 0)
        if fill_w > 2:
            c.setFillColor(self.accent)
            c.setStrokeColor(self.accent)
            c.roundRect(0, 0, fill_w, self.height, 3, stroke=1, fill=1)
        c.setStrokeColor(SAND)
        for i in range(1, int(self.max_score)):
            x = self.width * (i / self.max_score)
            c.line(x, 0, x, self.height)


class SectionBanner(Flowable):
    def __init__(self, text: str, width: float, accent: colors.Color):
        super().__init__()
        self.text = text
        self.width = width
        self.accent = accent
        self.height = 24

    def draw(self) -> None:
        c = self.canv
        c.setFillColor(CHARCOAL)
        c.setFont("Helvetica-Bold", 13)
        c.drawString(0, 10, self.text)
        # 2-tone underline: Gold then client accent
        c.setStrokeColor(GOLD)
        c.setLineWidth(2)
        c.line(0, 6, self.width * 0.6, 6)
        c.setStrokeColor(self.accent)
        c.line(self.width * 0.6, 6, self.width, 6)


class RecommendationChip(Flowable):
    """A pill-shaped chip in the accent color with the recommendation text."""

    def __init__(self, text: str, accent: colors.Color, width: float = 2.4 * inch, height: float = 22):
        super().__init__()
        self.text = text
        self.accent = accent
        self.width = width
        self.height = height

    def draw(self) -> None:
        c = self.canv
        c.setFillColor(self.accent)
        c.setStrokeColor(self.accent)
        c.roundRect(0, 0, self.width, self.height, self.height / 2, stroke=1, fill=1)
        c.setFillColor(colors.white)
        c.setFont("Helvetica-Bold", 10)
        c.drawCentredString(self.width / 2, self.height / 2 - 3.5, self.text)


# --- Styles -----------------------------------------------------------------

def build_styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    body = ParagraphStyle(
        "Body",
        parent=base["BodyText"],
        fontName="Helvetica",
        fontSize=9.5,
        leading=13,
        textColor=CHARCOAL,
    )
    small = ParagraphStyle(
        "Small",
        parent=body,
        fontSize=8.5,
        leading=11,
        textColor=TEXT_SECONDARY,
    )
    footer_brand = ParagraphStyle(
        "FooterBrand",
        parent=body,
        fontSize=8,
        leading=10,
        textColor=GOLD,
        fontName="Helvetica-Oblique",
    )
    header_title = ParagraphStyle(
        "HeaderTitle",
        parent=body,
        fontName="Helvetica-Bold",
        fontSize=20,
        leading=24,
        textColor=colors.white,
    )
    header_sub = ParagraphStyle(
        "HeaderSub",
        parent=body,
        fontName="Helvetica",
        fontSize=10,
        leading=13,
        textColor=WARM_WHITE,
    )
    label = ParagraphStyle(
        "Label",
        parent=body,
        fontName="Helvetica-Bold",
        fontSize=8.5,
        leading=10,
        textColor=TEXT_SECONDARY,
    )
    value = ParagraphStyle(
        "Value",
        parent=body,
        fontName="Helvetica",
        fontSize=10.5,
        leading=13,
        textColor=CHARCOAL,
    )
    h3 = ParagraphStyle(
        "H3",
        parent=body,
        fontName="Helvetica-Bold",
        fontSize=10.5,
        leading=13,
        textColor=CHARCOAL,
        spaceBefore=4,
        spaceAfter=2,
    )
    return {
        "body": body,
        "small": small,
        "footer_brand": footer_brand,
        "header_title": header_title,
        "header_sub": header_sub,
        "label": label,
        "value": value,
        "h3": h3,
    }


# --- Page template ----------------------------------------------------------

def make_page_template(
    doc_width: float,
    doc_height: float,
    accent: colors.Color,
    company_name: str,
):
    """Top-bar header strip + bottom-page TalentCollyde brand-impression footer."""

    def on_page(canv, doc):
        # Top strip — Charcoal
        canv.saveState()
        canv.setFillColor(CHARCOAL)
        canv.rect(0, doc_height - 0.35 * inch, doc_width, 0.35 * inch, fill=1, stroke=0)
        # Two-tone accent line just below
        canv.setFillColor(GOLD)
        canv.rect(0, doc_height - 0.42 * inch, doc_width * 0.55, 0.06 * inch, fill=1, stroke=0)
        canv.setFillColor(accent)
        canv.rect(doc_width * 0.55, doc_height - 0.42 * inch, doc_width * 0.45, 0.06 * inch, fill=1, stroke=0)
        # Top-bar copy: <Company> — Candidate Scorecard on left, date on right
        canv.setFillColor(colors.white)
        canv.setFont("Helvetica-Bold", 10)
        canv.drawString(0.6 * inch, doc_height - 0.25 * inch, f"{company_name} — Candidate Scorecard")
        canv.setFont("Helvetica", 9)
        canv.drawRightString(
            doc_width - 0.6 * inch,
            doc_height - 0.25 * inch,
            f"Generated {datetime.now().strftime('%Y-%m-%d')}",
        )
        # Bottom-page page number + confidentiality
        canv.setFont("Helvetica", 8)
        canv.setFillColor(TEXT_SECONDARY)
        canv.drawRightString(
            doc_width - 0.6 * inch,
            0.55 * inch,
            f"Page {doc.page}",
        )
        canv.drawString(0.6 * inch, 0.55 * inch, "Confidential — for hiring use only")
        # TalentCollyde brand-impression line (in Gold)
        canv.setFillColor(GOLD)
        canv.setFont("Helvetica-Oblique", 7.5)
        canv.drawString(
            0.6 * inch,
            0.38 * inch,
            "Generated by TalentCollyde Hire — talentcollyde.com",
        )
        canv.restoreState()

    frame = Frame(
        0.6 * inch,
        0.75 * inch,
        doc_width - 1.2 * inch,
        doc_height - 1.35 * inch,
        id="main",
        showBoundary=0,
    )
    return PageTemplate(id="main", frames=[frame], onPage=on_page)


# --- Section builders -------------------------------------------------------

def build_header_block(
    data: dict[str, Any],
    styles: dict[str, ParagraphStyle],
    accent: colors.Color,
    width: float,
) -> list[Flowable]:
    """Candidate identity + composite score + recommendation chip."""
    candidate = data.get("candidate") or {}
    cand_name = safe(candidate.get("name"))
    cand_title = safe(candidate.get("current_title"))
    cand_company = safe(candidate.get("current_company"))
    cand_location = safe(candidate.get("current_location") or candidate.get("location"))

    company = safe(data.get("company"))
    role = safe(data.get("role"))
    date = safe(data.get("date"))

    overall_score = float(data.get("overall_score") or 0)
    recommendation = safe(data.get("recommendation"), default="—")

    # Identity table
    id_rows = [
        [para("CANDIDATE", styles["label"]), para(cand_name, styles["value"])],
        [para("CURRENT", styles["label"]), para(f"{cand_title} · {cand_company}", styles["value"])],
        [para("LOCATION", styles["label"]), para(cand_location, styles["value"])],
        [para("HIRING FOR", styles["label"]), para(f"{role} · {company}", styles["value"])],
        [para("INTERVIEWED", styles["label"]), para(date, styles["value"])],
    ]
    id_tbl = Table(id_rows, colWidths=[1.05 * inch, width - 1.05 * inch])
    id_tbl.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("LINEBELOW", (0, 0), (-1, -2), 0.25, SAND),
            ]
        )
    )

    # Score / recommendation strip
    strip = Table(
        [
            [
                para("COMPOSITE SCORE", styles["label"]),
                para(f"{overall_score:.1f} / 5.0", styles["header_title"]),
                para("RECOMMENDATION", styles["label"]),
                para(recommendation, styles["header_title"]),
            ]
        ],
        colWidths=[1.4 * inch, 1.6 * inch, 1.6 * inch, width - 4.6 * inch],
    )
    strip.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), CHARCOAL),
                ("TEXTCOLOR", (0, 0), (-1, -1), colors.white),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("LEFTPADDING", (0, 0), (-1, -1), 10),
                ("RIGHTPADDING", (0, 0), (-1, -1), 10),
                ("TOPPADDING", (0, 0), (-1, -1), 10),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
            ]
        )
    )

    story: list[Flowable] = [
        id_tbl,
        Spacer(1, 10),
        strip,
        Spacer(1, 6),
        ScoreBar(overall_score, 5.0, width, accent, height=14),
    ]

    idq_note = data.get("idq_note")
    if idq_note:
        story.append(Spacer(1, 6))
        story.append(rp("<i>{note}</i>", styles["small"], note=safe(idq_note)))

    return story


def build_gates_block(data: dict[str, Any], styles, accent, width) -> list[Flowable]:
    gates = data.get("stage_1_gates") or []
    story: list[Flowable] = [
        SectionBanner("Stage 1 — Pass/Fail Gates", width, accent),
        Spacer(1, 4),
    ]
    rows = [[rp("<b>Gate</b>", styles["body"]), rp("<b>Result</b>", styles["body"]), rp("<b>Note</b>", styles["body"])]]
    if not gates:
        rows.append([para("—", styles["body"]), para("—", styles["body"]), para("No gates recorded.", styles["small"])])
    else:
        for g in gates:
            rows.append(
                [
                    para(safe(g.get("gate")), styles["body"]),
                    para(safe(g.get("result")).upper(), styles["body"]),
                    para(safe(g.get("note"), default=""), styles["body"]),
                ]
            )
    tbl = Table(rows, colWidths=[width * 0.45, width * 0.15, width * 0.40])
    tbl.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("BACKGROUND", (0, 0), (-1, 0), OFF_WHITE),
                ("LINEBELOW", (0, 0), (-1, 0), 0.4, GOLD),
                ("LINEBELOW", (0, 1), (-1, -1), 0.25, SAND),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    story.append(tbl)
    story.append(Spacer(1, 10))
    return story


def build_persona_block(data: dict[str, Any], styles, accent, width) -> list[Flowable]:
    persona = data.get("stage_2_persona") or {}
    primary = safe(persona.get("primary"))
    secondary = persona.get("secondary")
    story: list[Flowable] = [
        SectionBanner("Stage 2 — Persona Match", width, accent),
        Spacer(1, 4),
        rp("<b>Primary:</b> {primary}", styles["body"], primary=primary),
    ]
    if secondary:
        story.append(rp("<b>Secondary:</b> {secondary}", styles["body"], secondary=safe(secondary)))
    story.append(Spacer(1, 10))
    return story


def build_dimensions_block(data: dict[str, Any], styles, accent, width) -> list[Flowable]:
    dims = data.get("stage_3_dimensions") or []
    story: list[Flowable] = [
        SectionBanner("Stage 3 — Weighted Scoring", width, accent),
        Spacer(1, 4),
    ]
    header = [
        rp("<b>#</b>", styles["body"]),
        rp("<b>Dimension</b>", styles["body"]),
        rp("<b>Weight</b>", styles["body"]),
        rp("<b>Score</b>", styles["body"]),
        rp("<b>Rationale</b>", styles["body"]),
    ]
    rows = [header]
    for i, d in enumerate(dims, 1):
        score_raw = d.get("score")
        if score_raw is None or (isinstance(score_raw, str) and score_raw.strip().lower() in ("insufficient data", "idq")):
            score_str = "IDQ"
        else:
            try:
                score_str = f"{float(score_raw):.1f}"
            except (TypeError, ValueError):
                score_str = safe(score_raw)
        weight_raw = d.get("weight")
        try:
            weight_pct = float(weight_raw)
            # Allow weight as either fraction (0.25) or percentage (25)
            if weight_pct <= 1.0:
                weight_pct *= 100
            weight_str = f"{weight_pct:.0f}%"
        except (TypeError, ValueError):
            weight_str = safe(weight_raw)
        rows.append(
            [
                para(str(i), styles["body"]),
                para(safe(d.get("name")), styles["body"]),
                para(weight_str, styles["body"]),
                para(score_str, styles["body"]),
                para(safe(d.get("rationale")), styles["body"]),
            ]
        )
    tbl = Table(
        rows,
        colWidths=[width * 0.05, width * 0.22, width * 0.10, width * 0.10, width * 0.53],
        repeatRows=1,
    )
    tbl.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("BACKGROUND", (0, 0), (-1, 0), OFF_WHITE),
                ("LINEBELOW", (0, 0), (-1, 0), 0.4, GOLD),
                ("LINEBELOW", (0, 1), (-1, -1), 0.25, SAND),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    story.append(tbl)
    story.append(Spacer(1, 8))
    return story


def build_counter_cases_block(data: dict[str, Any], styles, accent, width) -> list[Flowable]:
    dims = data.get("stage_3_dimensions") or []
    counters = [(d.get("name"), d.get("counter_case")) for d in dims if d.get("counter_case")]
    if not counters:
        return []
    story: list[Flowable] = [
        SectionBanner("Stress-Test — Counter-Cases", width, accent),
        Spacer(1, 4),
        para("The strongest argument against each score. If a counter-case feels stronger than the score, the score is wrong.", styles["small"]),
        Spacer(1, 4),
    ]
    for name, cc in counters:
        story.append(rp("<b>{name}:</b> {cc}", styles["body"], name=safe(name), cc=safe(cc)))
        story.append(Spacer(1, 3))
    story.append(Spacer(1, 8))
    return story


def build_provenance_block(data: dict[str, Any], styles, accent, width) -> list[Flowable]:
    story: list[Flowable] = [
        SectionBanner("Provenance", width, accent),
        Spacer(1, 4),
    ]
    evidence = data.get("evidence_brief_path")
    if evidence:
        story.append(rp("<b>Evidence brief:</b> {ev}", styles["small"], ev=safe(evidence)))
    story.append(Spacer(1, 4))
    story.append(
        para(
            "Scoring follows evidence-first methodology: every dimension cites direct quotes from interview notes "
            "before a number is assigned. Scores carry to 0.1 precision. Round numbers (X.0, X.5) require explicit "
            "anchor justification. Insufficient-Data dimensions are flagged and have their weight redistributed — "
            "never estimated.",
            styles["small"],
        )
    )
    story.append(Spacer(1, 6))
    story.append(HRule(width, SAND))
    story.append(Spacer(1, 4))
    story.append(para(TC_FOOTER_LINE, styles["footer_brand"]))
    return story


# --- Main -------------------------------------------------------------------

def build_pdf(
    data: dict[str, Any],
    output_path: str,
    client_accent: colors.Color,
    company_name: str,
) -> None:
    page_w, page_h = LETTER
    doc = BaseDocTemplate(
        output_path,
        pagesize=LETTER,
        leftMargin=0.6 * inch,
        rightMargin=0.6 * inch,
        topMargin=0.6 * inch,
        bottomMargin=0.6 * inch,
        title=f"Scorecard — {safe(data.get('candidate', {}).get('name'))} / {safe(data.get('role'))}",
        author=f"{company_name} (via TalentCollyde Hire)",
    )
    doc.addPageTemplates([make_page_template(page_w, page_h, client_accent, company_name)])

    styles = build_styles()
    content_w = page_w - 1.2 * inch

    story: list[Flowable] = []
    story.append(Spacer(1, 18))  # clear the top header strip
    story.extend(build_header_block(data, styles, client_accent, content_w))
    story.append(Spacer(1, 12))
    story.extend(build_gates_block(data, styles, client_accent, content_w))
    story.extend(build_persona_block(data, styles, client_accent, content_w))
    story.extend(build_dimensions_block(data, styles, client_accent, content_w))
    story.extend(build_counter_cases_block(data, styles, client_accent, content_w))
    story.extend(build_provenance_block(data, styles, client_accent, content_w))

    doc.build(story)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate a 2-page branded TalentCollyde Hire scorecard PDF.")
    parser.add_argument("--input", required=True, help="Path to scorecard JSON data")
    parser.add_argument("--output", required=True, help="Output PDF path")
    parser.add_argument(
        "--client-accent",
        default=None,
        help="Company accent color as a hex code (e.g. '#FE5A27'). Defaults to TalentCollyde Gold #c9a96e.",
    )
    parser.add_argument(
        "--company-name",
        default="Company",
        help="Hiring company name (rendered in top-bar header). Defaults to 'Company'.",
    )
    args = parser.parse_args(argv)

    if not os.path.exists(args.input):
        sys.stderr.write(f"ERROR: input file not found: {args.input}\n")
        return 2

    with open(args.input, "r", encoding="utf-8") as fh:
        try:
            data = json.load(fh)
        except json.JSONDecodeError as e:
            sys.stderr.write(f"ERROR: failed to parse JSON: {e}\n")
            return 2

    # Prefer the company name from the JSON if present
    company_name = data.get("company") or args.company_name

    # Prefer the accent from the JSON if present
    accent_hex = data.get("accent_hex") or args.client_accent
    accent = hex_or_default(accent_hex)

    os.makedirs(os.path.dirname(os.path.abspath(args.output)) or ".", exist_ok=True)
    build_pdf(data, args.output, accent, company_name)
    print(f"Wrote scorecard to {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
